//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.17929
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.Michelin2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Michelin2.IServiceMichelin")]
    public interface IServiceMichelin {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceMichelin/GetPrix", ReplyAction="http://tempuri.org/IServiceMichelin/GetPrixResponse")]
        int GetPrix(string typepneu);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceMichelinChannel : WpfApplication1.Michelin2.IServiceMichelin, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceMichelinClient : System.ServiceModel.ClientBase<WpfApplication1.Michelin2.IServiceMichelin>, WpfApplication1.Michelin2.IServiceMichelin {
        
        public ServiceMichelinClient() {
        }
        
        public ServiceMichelinClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceMichelinClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMichelinClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceMichelinClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetPrix(string typepneu) {
            return base.Channel.GetPrix(typepneu);
        }
    }
}
